build: off
shallow_clone: true
version: '{build}'
skip_tags: true

environment:
  matrix:
    - nodejs_version: '5'
    - nodejs_version: '0'
    - nodejs_version: '0.10'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@latest
  - npm install

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - npm test
